name: tmallkorea
favicon: null
layout_spectrum: 0.13151090499013662
typography_spectrum: 0.0014426540583372116
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2461120702791959
  lightness: 0.15032481914386153
  saturation: 0.7624002022203058
  rhythmicContrast: 0.19687025086022913
purpose: []
