typography_spectrum: 0.47607
color:
  brandColors:
    - '#fefefe'
    - '#d20104'
    - '#ff4d4d'
    - '#677c9b'
    - '#353439'
  brandStrength: 0.5
  lightness: 0.15032481914386153
  saturation: 0.7624002022203058
  rhythmicContrast: 0.19687025086022913
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4988
analytics:
  google: null
  facebook: null
  twitter: null
name: tmallkorea
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: (주)우림하이텍
purpose: []
