typography_spectrum: 0.47607
color:
  brandColors:
    - '#fefefe'
    - '#d20104'
    - '#ff4d4d'
    - '#677c9b'
    - '#353439'
  brandStrength: 0.5
  lightness: 0.15032481914386153
  saturation: 0.7624002022203058
  rhythmicContrast: 0.19687025086022913
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4988
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: maxdm
  email: maxdm8404@daum.net
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7f0909ce-7da7-4297-8e7a-8a7c4ad9d571.png
name: woolimhitek
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 브랜드 미션 정하는법
    id: 450689e9-9bfa-485d-addd-5a4e1f280123
    type: content
favicon: null
title: (주)우림하이텍
description: 융복합 6차산업 홈페이짖제작 전문기업
purpose: []
